### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by johannbrehmer**
This PR adds support for running PySR on Windows, fixing #17.

- [x] Use pathlib to specify and operate with filenames
- [x] Escape backslashes from Windows filenames in Julia script
- [x] Use tempfile for the creation of the temporary files / folder
- [x] Add keywords for user-defined temporary file locations and to spare them from deletion
- [x] Test on Linux
- [x] Test on MacOS
- [x] Test on Windows

### CODE REVIEW

**Comment by johannbrehmer** [comment]
Success (mostly). This current version works with Python 3.8 under Windows and Mac OS (and since it passes CI, I assume also under Linux?).

However, under Windows for some reason you have to run `using SpecialFunctions` and `using Optim` in Julia to trigger some form of precompilation before running PySR... I'm not sure how to solve this, I could add a comment on that to the README?

**Comment by MilesCranmer** [comment]
Awesome, thanks so much @johannbrehmer!! Sorry that it was tricky to fix the filepaths for Windows.

I will review this PR this afternoon and then merge.

Re: importing packages, do you mean it won't run PySR unless you precompile those packages beforehand? I think it should precompile them the first time it runs PySR, no?

Alternatively I think installing with: 
```bash
  for PKG in "Optim" "SpecialFunctions"; do
    echo "Installing Julia package $PKG..."
    julia -e 'using Pkg; pkg"add '$PKG'; precompile;"'
  done
```
should also precompile them. I could add this advice to the README.

**Comment by MilesCranmer** [comment]
Also, let me add a CI for Windows testing.

**Comment by johannbrehmer** [comment]
> Re: importing packages, do you mean it won't run PySR unless you precompile those packages beforehand?

Yes, exactly. Here's the error message I got under Windows if I *didn't* precompile these packages before running PySR:

```
ERROR: LoadError: On worker 2:
LoadError: Failed to precompile Optim [429524aa-4258-5aef-a3af-852621145aeb] to C:\Users\thali\.julia\compiled\v1.5\Optim\R5uoh_MiN5M.ji.
error at .\error.jl:33
compilecache at .\loading.jl:1305
_require at .\loading.jl:1030
require at .\loading.jl:928
require at .\loading.jl:923
include at .\client.jl:457
top-level scope at none:1
eval at .\boot.jl:331
#103 at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Distributed\src\process_messages.jl:290
run_work_thunk at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Distributed\src\process_messages.jl:79
run_work_thunk at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Distributed\src\process_messages.jl:88
#96 at .\task.jl:356
in expression starting at c:\users\thali\pysr\pysr\julia\sr.jl:1
...and 4 more exception(s).
```

This happened on two separate computers running Windows, but not on a third running Mac OS. It was fixed by running the two `using` statements in Julia.

Adding CI for Windows is great! And adding that advice to the README can't hurt.

**Review by MilesCranmer — APPROVED** [review]
These changes look great! Seems like the minimal amount of complexity added to get it working on Windows, which is really nice.

**Pull request merged**
