### PR TITLE
fix TypeError when a variable name matches a builtin python function

### PR DESCRIPTION
**Pull request by tomjelen**
For example, fitting on a dataset with a column named 'exec' fails with:

```
ValueError: Error from parse_expr with transformed code: "(Float ('86.76248' )-exec )" 
... snip ...
TypeError: unsupported operand type(s) for -: 'Float' and 'builtin_function_or_method'
```

This change maps the feature names to sympy.Symbol when parsing the pysr-equation in `pysr2sympy`.

### CODE REVIEW

**Comment by MilesCranmer** [comment]
Thanks!

**Comment by MilesCranmer** [comment]
@tomjelen can you enable push access for maintainers? Then I can edit the PR directly.

**Comment by tomjelen** [comment]
Hey there, thanks for looking into the failed build. I don't have much experience with Conda, so could take me a while to figure out whats going on.

"Allow edits by maintainers" is checked. That's what you need right?

**Comment by MilesCranmer** [comment]
Perfect, thanks!

The segfault looks to be unrelated. Sometimes the GitHub action runners simply don't enough memory to use for the builds. But I will take a look.

**Comment by MilesCranmer** [comment]
Hm, nope, it's still not letting me push to your branch. It says 

```
! [remote rejected] tomjelen/master -> tomjelen/master (permission denied)
```

I can also make a new PR from my local branch if needed, including your commit as the base.

**Comment by MilesCranmer** [comment]
Nevermind, seems like it was some issue on my side with remotes and what URL I used... Sorry for the confusion

**Review by MilesCranmer — APPROVED** [review]

**Comment by tomjelen** [comment]
Ah, okay. No worries :)

**Pull request merged**
